### ISSUE TITLE
Completar listado de requerimientos funcionales

### ISSUE THREAD

**Issue by li0t** [li0t/dacomment#12]
- [x] El nombre debe ser Requerimientos Funcionales en vez de Funcionalidades del Sistema.
- [x] Insertar comentario a archivo por versión es parte de la funcionalidad versionar archivo, se propone fusionarla en Versionar Archivo con comentario.
- [x] Agregar documento a portafolio, en vez de Asignar documento a portafolio.
- [x] Visualizar diferencias de archivo por versión, en vez de Informar.
- [x] Propongo eliminar el requerimiento Informar diferencias de archivo por versión y usuario (No aporta valor a esta entrega).
- [x] Se propone reemplazar las palabras Retirar y Denegar por Remover y/o Eliminar.

**Comment by Lezier** [comment]
1. No se realiza cambio de Funcionalidades a Requerimientos Funcionales, ya que no son requerimientos, en caso de generar cambio, se debería identificar, definir y especificar cada requerimiento.
2. No se unen funcionalidades, si bien tienen una dependencia de causa efecto, son dos acciones independientes en sistema.
3. Cambio realizado
4. Cambio realizado 
5. Cambio realizado 
6. Se cambia retirar, "denegar" se cambia por "quitar"

**Comment by li0t** [comment]
Permanecen algunas funcionalidades con "Denegar".
Se pide cambiar por "Quitar" para mantener consistencia a través del documento.

**Diagrama:**  No se està trabajando con un modelo de entidad en CodeIgniter, se propone fucionar el componente de operaciones con el componente de entidad en un solo componente llamado **Modelo**, que se corresponde con la estructura definida en el código del proyecto.
