### ISSUE TITLE
Testing exhaustivo.

### ISSUE THREAD

**Issue by li0t** [li0t/dacomment#17]

**Comment by li0t** [comment]
Se espera revisar y reportar:
- [x] Requerimientos funcionales no cumplidos.
- [x] Flujos de navegaciones incorrectos o mal diseñados.
- [x] Elementos gráficos no resueltos.

**Comment by Lezier** [comment]
_Funcionalidades cumplidas:_
- Subir archivo. (importante)
- Descargar archivo. (importante)
- Versionar archivo. (importante)
- Insertar comentario a archivo por versión. (importante)
- Asignar permisos de colaboración a archivo. (importante)
- Asignar permisos de vista a archivo. (importante)
- Quitar permisos de colaboración a archivo. (importante)
- Quitar permisos de vista a archivo. (importante)
- Crear portafolio. (opcional)
- Agregar documento a portafolio. (opcional)
- Remover documento de portafolio. (opcional)
- Asignar permiso de vista a portafolio. (opcional)
- Asignar permiso de colaboración a portafolio. (opcional)
- Quitar permiso de vista a portafolio. (opcional)
- Quitar permiso de colaboración a portafolio. (opcional)
- Autenticar usuario. (opcional)

_Flujos de navegación_
- No se detectan vinculos rotos y/o elementos sin resolver comunicación 

_Elementos gráficos no resueltos_
- Cambiar en la base de datos a cacapichi.
- Ocultar tab usuarios.
